// hcol-bcol-probe: read a single block's header + body via the
// columnar readers and report whether the format round-trips with
// the current code. Useful when older N42 columnar files may have
// been generated by a slightly different encoder.
package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/n42blockchain/N42/internal/ethel"
)

func main() {
	dir := flag.String("dir", "", "freezer dir with hcol.cidx + bcol.cidx")
	block := flag.Uint64("block", 0, "block to probe")
	bench := flag.Uint64("bench", 0, "if >0, sequentially read N blocks from --block and report rate")
	flag.Parse()
	if *dir == "" {
		fmt.Fprintln(os.Stderr, "usage: hcol-bcol-probe --dir <freezer> --block N")
		os.Exit(1)
	}

	hr, err := ethel.OpenHeaderCompact(*dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "open hcol:", err)
		os.Exit(1)
	}
	defer hr.Close()
	fmt.Printf("hcol segments=%d max_block=%d\n", hr.Segments(), hr.MaxBlock())

	hdr, err := hr.ReadHeader(*block)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read header %d: %v\n", *block, err)
	} else {
		fmt.Printf("hdr[%d]: hash=%x parent=%x gasUsed=%d txRoot=%x receiptRoot=%x bloom_first16=%x\n",
			*block, hdr.Hash(), hdr.ParentHash, hdr.GasUsed, hdr.TxHash, hdr.ReceiptHash, hdr.Bloom[:16])
	}

	br, err := ethel.OpenBodyCompact(*dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "open bcol:", err)
		os.Exit(1)
	}
	defer br.Close()
	fmt.Printf("bcol segments=%d max_block=%d\n", br.Segments(), br.MaxBlock())

	body, err := br.ReadBody(*block)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read body %d: %v\n", *block, err)
		os.Exit(1)
	}
	fmt.Printf("body[%d]: txs=%d uncles=%d withdrawals=%d\n",
		*block, len(body.Txs), len(body.UncleRLP), len(body.Withdrawals))
	for i, tx := range body.Txs {
		if i >= 3 {
			fmt.Printf("  ...+%d more txs\n", len(body.Txs)-3)
			break
		}
		fmt.Printf("  tx[%d] hash=%x type=%d nonce=%d gas=%d\n",
			i, tx.Hash(), tx.Type(), tx.Nonce(), tx.Gas())
	}

	if *bench > 0 {
		fmt.Printf("\n=== sequential read bench: %d blocks from %d ===\n", *bench, *block)
		t0 := time.Now()
		var totalTxs int
		for n := *block; n < *block+*bench; n++ {
			b, err := br.ReadBody(n)
			if err != nil {
				fmt.Fprintf(os.Stderr, "block %d: %v\n", n, err)
				os.Exit(1)
			}
			totalTxs += len(b.Txs)
		}
		bodyDur := time.Since(t0)
		fmt.Printf("body bench: %d blocks, %d txs, %s, %.0f blk/s\n",
			*bench, totalTxs, bodyDur.Truncate(time.Millisecond), float64(*bench)/bodyDur.Seconds())

		t0 = time.Now()
		for n := *block; n < *block+*bench; n++ {
			h, err := hr.ReadHeader(n)
			if err != nil {
				fmt.Fprintf(os.Stderr, "header %d: %v\n", n, err)
				os.Exit(1)
			}
			_ = h.Hash()
		}
		hdrDur := time.Since(t0)
		fmt.Printf("header bench: %d blocks, %s, %.0f blk/s\n",
			*bench, hdrDur.Truncate(time.Millisecond), float64(*bench)/hdrDur.Seconds())
	}
}
