// headerc-bodyc-probe: read a single block's header + body via the
// columnar readers and report whether the format round-trips with
// the current code. Useful when older N42 columnar files may have
// been generated by a slightly different encoder.
package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"math/big"

	"github.com/holiman/uint256"

	"github.com/n42blockchain/N42/common/transaction"
	"github.com/n42blockchain/N42/internal/ethel"
	"github.com/n42blockchain/N42/params"
)

func main() {
	dir := flag.String("dir", "", "freezer dir with headerc.cidx + bodyc.cidx")
	block := flag.Uint64("block", 0, "block to probe")
	bench := flag.Uint64("bench", 0, "if >0, sequentially read N blocks from --block and report rate")
	flag.Parse()
	if *dir == "" {
		fmt.Fprintln(os.Stderr, "usage: headerc-bodyc-probe --dir <freezer> --block N")
		os.Exit(1)
	}

	hr, err := ethel.OpenHeaderCompact(*dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "open headerc:", err)
		os.Exit(1)
	}
	defer hr.Close()
	fmt.Printf("headerc segments=%d max_block=%d\n", hr.Segments(), hr.MaxBlock())

	hdr, err := hr.ReadHeader(*block)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read header %d: %v\n", *block, err)
	} else {
		fmt.Printf("hdr[%d]: hash=%s coinbase=%s gasUsed=%d gasLimit=%d time=%d difficulty=%s stateRoot=%s txRoot=%s receiptRoot=%s\n",
			*block, hdr.Hash().Hex(), hdr.Coinbase.Hex(), hdr.GasUsed, hdr.GasLimit, hdr.Time, hdr.Difficulty.String(), hdr.Root.Hex(), hdr.TxHash.Hex(), hdr.ReceiptHash.Hex())
	}

	br, err := ethel.OpenBodyCompact(*dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "open bodyc:", err)
		os.Exit(1)
	}
	defer br.Close()
	fmt.Printf("bodyc segments=%d max_block=%d\n", br.Segments(), br.MaxBlock())

	body, err := br.ReadBody(*block)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read body %d: %v\n", *block, err)
		os.Exit(1)
	}
	fmt.Printf("body[%d]: txs=%d uncles=%d withdrawals=%d\n",
		*block, len(body.Txs), len(body.UncleRLP), len(body.Withdrawals))
	for i, tx := range body.Txs {
		if i >= 3 {
			fmt.Printf("  ...+%d more txs\n", len(body.Txs)-3)
			break
		}
		toStr := "nil"
		if tx.To() != nil {
			toStr = fmt.Sprintf("0x%x", *tx.To())
		}
		v, r, s := tx.RawSignatureValues()
		fmt.Printf("  tx[%d] hash=%x\n    type=%d nonce=%d gas=%d gasPrice=%s value=%s to=%s\n    V=%s R=%s S=%s\n",
			i, tx.Hash(), tx.Type(), tx.Nonce(), tx.Gas(),
			tx.GasPrice().String(), tx.Value().String(), toStr,
			v.String(), r.String(), s.String())
		gasCost := new(uint256.Int).Mul(tx.GasPrice(), uint256.NewInt(tx.Gas()))
		needed := new(uint256.Int).Add(gasCost, tx.Value())
		fmt.Printf("    gasCost=%s needed(gas+value)=%s\n", gasCost.String(), needed.String())
		signer := transaction.MakeSignerWithTimestamp(params.EthereumMainnetChainConfig, big.NewInt(int64(*block)), 0)
		sender, err := transaction.Sender(signer, tx)
		if err != nil {
			fmt.Printf("    ecrecover ERR: %v\n", err)
		} else {
			fmt.Printf("    ecrecovered sender = 0x%x\n", sender)
		}
	}

	if *bench > 0 {
		fmt.Printf("\n=== sequential read bench: %d blocks from %d ===\n", *bench, *block)
		t0 := time.Now()
		var totalTxs int
		for n := *block; n < *block+*bench; n++ {
			b, err := br.ReadBody(n)
			if err != nil {
				fmt.Fprintf(os.Stderr, "block %d: %v\n", n, err)
				os.Exit(1)
			}
			totalTxs += len(b.Txs)
		}
		bodyDur := time.Since(t0)
		fmt.Printf("body bench: %d blocks, %d txs, %s, %.0f blk/s\n",
			*bench, totalTxs, bodyDur.Truncate(time.Millisecond), float64(*bench)/bodyDur.Seconds())

		t0 = time.Now()
		for n := *block; n < *block+*bench; n++ {
			h, err := hr.ReadHeader(n)
			if err != nil {
				fmt.Fprintf(os.Stderr, "header %d: %v\n", n, err)
				os.Exit(1)
			}
			_ = h.Hash()
		}
		hdrDur := time.Since(t0)
		fmt.Printf("header bench: %d blocks, %s, %.0f blk/s\n",
			*bench, hdrDur.Truncate(time.Millisecond), float64(*bench)/hdrDur.Seconds())
	}
}
