// Copyright 2022-2026 The N42 Authors
// This file is part of the N42 library.
//
// The N42 library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The N42 library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the N42 library. If not, see <http://www.gnu.org/licenses/>.

package vm

import (
	"testing"
)

// TestVMTAbsintGenCfgAndProofRoundTrip drives the pure abstract-interpretation
// CFG builder (GenCfg) over a tiny, deterministic piece of bytecode with a
// conditional jump, generates a proof, and round-trips it through
// Serialize/DeserializeCfgProof and Compress/DecompressProof, finally
// checking it with the independent CheckCfg verifier.
func TestVMTAbsintGenCfgAndProofRoundTrip(t *testing.T) {
	// PUSH1 0x07; PUSH1 0x01; JUMPI; STOP; JUMPDEST(pc7); PUSH1 0x2a; STOP
	code := []byte{
		byte(PUSH1), 0x07, // pc0,1
		byte(PUSH1), 0x01, // pc2,3 cond = 1
		byte(JUMPI), // pc4
		byte(STOP),  // pc5 (not taken)
		byte(0),     // pc6 padding
		byte(JUMPDEST), // pc7
		byte(PUSH1), 0x2a, // pc8,9
		byte(STOP), // pc10
	}

	metrics := &CfgMetrics{}
	cfg, err := GenCfg(code, 10_000, 64, 10_000, metrics)
	if err != nil {
		t.Fatalf("GenCfg failed: %v", err)
	}
	if !metrics.Valid {
		t.Fatalf("expected metrics.Valid, got %+v", metrics)
	}

	proof := cfg.GenerateProof()
	if proof == nil {
		t.Fatalf("GenerateProof returned nil")
	}
	if !proof.isValid() {
		t.Fatalf("generated proof reports itself invalid")
	}

	serialized := proof.Serialize()
	if len(serialized) == 0 {
		t.Fatalf("Serialize returned empty bytes")
	}

	roundTripped := DeserializeCfgProof(serialized)
	if roundTripped == nil {
		t.Fatalf("DeserializeCfgProof returned nil")
	}

	compressed := CompressProof(serialized)
	if len(compressed) == 0 {
		t.Fatalf("CompressProof returned empty bytes")
	}
	decompressed := DecompressProof(compressed)
	if len(decompressed) != len(serialized) {
		t.Fatalf("round-trip length mismatch: got %d want %d", len(decompressed), len(serialized))
	}

	if !CheckCfg(code, roundTripped) {
		t.Fatalf("CheckCfg rejected a proof generated by GenCfg for its own code")
	}

	// GetCodeHex and String/ToString must not panic and should be non-empty.
	if cfg.Program.GetCodeHex() == "" {
		t.Fatalf("expected non-empty code hex")
	}
	if proof.ToString() == "" {
		t.Fatalf("expected non-empty proof string")
	}

	stats := cfg.GetCoverageStats()
	if stats.Covered == 0 {
		t.Fatalf("expected at least one covered instruction")
	}
}

// TestVMTAbsintCheckCfgRejectsTamperedProof verifies CheckCfg rejects a
// proof whose code does not match (a basic negative-path sanity check for
// the independent verifier).
func TestVMTAbsintCheckCfgRejectsTamperedProof(t *testing.T) {
	code := []byte{
		byte(PUSH1), 0x05,
		byte(JUMP),
		byte(0), byte(0),
		byte(JUMPDEST),
		byte(STOP),
	}
	metrics := &CfgMetrics{}
	cfg, err := GenCfg(code, 10_000, 64, 10_000, metrics)
	if err != nil {
		t.Fatalf("GenCfg failed: %v", err)
	}
	proof := cfg.GenerateProof()

	otherCode := []byte{byte(STOP)}
	if CheckCfg(otherCode, proof) {
		t.Fatalf("CheckCfg unexpectedly accepted a proof for mismatched code")
	}
}
